### ISSUE TITLE
Initiate package review request

### ISSUE THREAD

**Issue by eboylestanley** [UBC-MDS/coRPysprofiling-R#31]

**Comment by ssyayayy** [comment]
Submitting Author: Anita Li (@AnitaLi-0371), Elanor Boyle-Stanley (@eboylestanley), Junghoo Kim (@jkim222383), Ivy Zhang (@ssyayayy)
Repository: https://github.com/UBC-MDS/coRPysprofiling-R/releases/tag/v0.3.0
Version submitted: v0.3.0
Editor:  Tiffany Timbers(@ttimbers ) 
Reviewers:  TBD 

Archive: TBD
Version accepted: TBD

---



-   Paste the full DESCRIPTION file inside a code block below: [need to be updated once version is finalized]()

```
Package: coRPysprofiling
Title: R Package for EDA and EDV on text
Version: 0.0.0.9000
Authors@R: 
    c(person(given = "Anita",
             family = "Li",
             role = c("aut"),
             email = "anita.li.ubc@gmail.com"),
      person(given = "Elanor",
             family = "Boyle-Stanley",
             role = c("aut"),
             email = "elanor.boyle.stanley@gmail.com"),
      person(given = "Junghoo",
             family = "Kim",
             role = c("aut"),
             email = "jkim.222383@gmail.com"),
      person(given = "Ivy",
             family = "Zhang",
             role = c("aut", "cre"),
             email = "ivyzhang1017@hotmail.com"))
Description: coRPysprofiling is an open-source library designed to bring exploratory 
    data analysis and visualization to the domain of natural language processing. 
    Functions in the package will be used to provide some elementary statistics and 
    visualizations for a single text corpus or provide functions to compare multiple 
    corpora with each other.
License:  GPL-3
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Suggests: 
    testthat (>= 3.0.0),
    covr,
    knitr,
    rmarkdown
Config/testthat/edition: 3
Imports: 
    stopwords,
    tokenizers,
    word2vec,
    stringr,
    here,
    stringi,
    ggplot2,
    ggwordcloud,
    dplyr
VignetteBuilder: knitr
```


## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [X] data retrieval
	- [ ] data extraction
	- [ ] data munging
	- [ ] data deposition
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [X] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):
> The core functionalities for `coRPysprofiling` are to provide elementary statistics and visualizations for a single text corpus, and to compare multiple corpora with each other.  It can also download and load pretrained word2vector models from github repository.
-   Who is the target audience and what are scientific applications of this package?
> The target audience can be talent acquisition specialists who want to quickly retrieve valuable information from resume texts or compare text from two resumes. 
-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?
> To our knowledge, while wordcloud library generates wordcloud visualization for a given corpus, there is no general-purpose library for exploratory analysis and visualization of a text corpus in the R ecosystem. There are several advanced libraries for comparing similarities between different corpora: most notably, quanteda provides similarity comparison between large corpora using word embeddings. We believe that coRPysprofiling will provide some useful functionality for exploratory analysis and visualization and help bridge the gap between elementary text analysis to more sophisticated approaches utilizing word embeddings.
-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?
> Not applicable
-   If you made a pre-submission enquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.
> Not applicable

## Technical checks

Confirm each of the following by checking the box.

- [X] I have read the [guide for authors](https://devguide.ropensci.org/guide-for-authors.html) and [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).

This package:

- [X] does not violate the Terms of Service of any service it interacts with.
- [X] has a CRAN and OSI accepted license.
- [X] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [X] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [X] contains a vignette with examples of its essential functions and uses.
- [X] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [X] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage using services such as Travis CI, Coveralls and/or CodeCov.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [X] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.github.io/dev_guide/policies.html#code-of-conduct) during the review process and in maintaining my package should it be accepted.

**Comment by ssyayayy** [comment]
Created package review request in software-review-2021 repo. 
Here is the link: https://github.com/UBC-MDS/software-review-2021/issues/39
